name: Community Proposal
description: Submit a proposal for funding.
title: "[Community Proposal]: "
labels: ["For Review", "Funding Proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this funding request!

  - type: markdown
    attributes:
      value: |
        Please review the process in the [Jupyter Governance](https://github.com/jupyter-governance/community-proposals)

  - type: markdown
    attributes:
      value: |
        Qualifying Information
  - type: input
    id: initiative
    attributes:
      label: Initiative
      description: Which initiative is requesting the funds?
      placeholder: an existing Jupyter working group, special interest group, or project
    validations:
      required: true
  - type: input
    id: funding-amount
    attributes:
      label: Funding Amount
      description: What is the exact amount of funding you're requesting?
      placeholder: "$1000"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Problem statement - This section aims to set the stage and boundaries for the problem you are trying to solve. This is not a place to propose solutions, but to define the problem and its impact.
  - type: input
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What is the problem?
    validations:
      required: true
  - type: input
    id: affects
    attributes:
      label: Who does this affect?
      description: Who does this problem impact, and for whom is this solution?
    validations:
      required: true
  - type: input
    id: why-now
    attributes:
      label: Why should it be tackled now and by this initiative?
      description: Is this the right place and time for this funding initiative?
    validations:
      required: true
  - type: input
    id: responsible-party
    attributes:
      label: Who is responsible for doing the work of this funding initiative?
      description: This person is the primary contact to oversee the idea
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Jupyter Foundation Code of Conduct](https://google.com) to ensure an inclusive environment for participants.
      options:
        - label: I agree to follow the Jupyter Foundation's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        The final section is to list the Milestones and Approximate costs associated with the funding initiative. If you prefer, you can submit a Google Sheet or Google Doc in the entry below.

  - type: markdown
    attributes:
      value: |
        Thanks for completing this form! If you have any problems, questions or concerns, please email us at [operations@jupyterfoundation.org](mailto:operations@jupyterfoundation.org).
